org: oskstr
app: swe-vaccine-count
service: swe-vaccine-count

provider:
  name: aws
  iamRoleStatements:
     - Effect: Allow
       Action:
         - dynamodb:PutItem
       Resource: "*"
  region: eu-west-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    TWITTER_CONSUMER_KEY: ${param:consumer_key, env:consumer_key}
    TWITTER_CONSUMER_SECRET: ${param:consumer_secret, env:consumer_secret}
    TWITTER_ACCESS_TOKEN_KEY: ${param:access_token_key, env:access_token_key}
    TWITTER_ACCESS_TOKEN_SECRET: ${param:access_token_secret, env:access_token_secret}

functions:
  vaccine-count:
    handler: handler.vaccineCount
    events:
      - schedule: rate(10 minutes)

resources:
  Resources:
    vaccineCount:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: vaccineCount
        AttributeDefinitions:
          - AttributeName: mostRecent
            AttributeType: S 
        KeySchema:
          - AttributeName: mostRecent
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-plugin-typescript
  - serverless-offline
